name: financial_chart
description: A chart library for financial data. supports candlestick, ohlc, line, area charts and custom chart types.
repository: https://github.com/cjjapan/financial_chart
homepage: https://github.com/cjjapan/financial_chart
topics:
  - chart
  - charts
  - graph
  - candlestick
  - stock
# publish_to: "none"

version: 0.1.2+1

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ^0.20.1
  path_drawing: ^1.0.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lints: ^2.1.1

flutter:
  uses-material-design: true
